- name: Remove Bloat
  dnf:
    name:
      - "libreoffice*"
      - gnome-calendar
      - gnome-characters
      - gnome-contacts
      - gnome-maps
      - gnome-tour
      - gnome-logs
      - yelp
      - snapshot
      - mediawriter
      - simple-scan
    state: absent
    autoremove: true
    tags: bloat
