- name: Set ZSH as the default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Edit DNF config
  blockinfile:
    path: "/etc/dnf/dnf.conf"
    marker: "# {mark} ANSIBLE MANAGED OPTIONS"
    block: |
      fastestmirror=True
      max_parallel_downloads=10
      defaultyes=True
      keepcache=True

- name: Check if Oh My Zsh is already installed
  stat:
    path: "~{{ ansible_user_id }}/.oh-my-zsh"
  register: oh_my_zsh_stat
  become: false

- name: Install Oh My Zsh unattended
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: "{{ ansible_user_id }}"
  when: not oh_my_zsh_stat.stat.exists
  become: false

- name: Set Oh My Zsh Theme
  lineinfile:
    path: "~{{ ansible_user_id }}/.zshrc"
    regexp: "^ZSH_THEME=.*"
    line: 'ZSH_THEME="half-life"'
    state: present
  become_user: "{{ ansible_user_id }}"
  become: false

- name: Configure Oh My Zsh Plugins in .zshrc
  lineinfile:
    path: "~{{ ansible_user_id }}/.zshrc"
    regexp: '^plugins=\(.*\)'
    line: "plugins=(git fedora sudo)"
    state: present
  become_user: "{{ ansible_user_id }}"
  become: false
